### PR TITLE
fixed the skills section issue

### PR DESCRIPTION
**Pull request by Pulkitxm**
https://github.com/thesidshah/my-website/assets/65671483/7d52293f-89ca-4af3-8c82-d542ef3e63f9

fixed the skills section issue 
feel free to make further changes in the frontend and backend components

### CODE REVIEW

**Comment by thesidshah** [comment]
Great work @Pulkitxm ! I will definitely go through the code later tomorrow.

**Review by thesidshah — COMMENTED** [review]
The code is amazing to set a baseline, I will be changing a few things to go with the website: Given that I am already working on another feature: timeline, I will have to push that to tomorrow.

Before changing I will put out a set of comments about the why

**Comment by Pulkitxm** [comment]
So please merge the PR

**Comment by thesidshah** [comment]
> So please merge the PR

Working on it!

**Pull request merged**
